### ISSUE TITLE
Issue in Exercise-1/Task-3/Step-28

### ISSUE THREAD

**Issue by Divyasri199** [microsoft/MCW-Building-a-resilient-IaaS-architecture#101]
In [Exercise-1/Task-3/Step-28](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Building%20a%20resilient%20IaaS%20architecture.md#task-3-configure-ha-for-the-sql-server-tier), we are facing an issue while connecting to the SQL server studio using the provided credentials. I have tried it in 2 environments and met the same issue in both environments.

We have a workshop scheduled for 28th June. Please consider this a high priority and provide us with a workaround ASAP.

![image](https://user-images.githubusercontent.com/83349577/175096064-33619ec2-3ee8-412d-9fcb-845fccaf0ba6.png)

**Comment by benstegink** [comment]
@Divyasri199 
1. You could double check you reconfigured all the services to run under the domain account and didn't accidentally skip over one of those steps.
2. If you need to work around, go back to step 8 (logging in with Bastion) and use the local admin instead of the domain account to log into the VM, then use the local admin to add contoso\demouser as a sysadmin in SQL. Once contoso\demouser has been added as a sysadmin, step 28 should work fine

**Comment by DawnmarieDesJardins** [comment]
@Divyasri199 - Please test the changes made to the script and let us know if it's working for you. Thanks
