### ISSUE TITLE
ASR should feature more prominently 

### ISSUE THREAD

**Issue by bendq** [Microsoft/MCW-Building-a-resilient-IaaS-architecture#18]
ASR is currently discounted as scale sets are not supported. I believe scale sets are not something that would lend well to DR/backup anyway as they are based on repeatable templates which generally have not requirement for traditional DR/Backup. 

I would look at maybe adding more around our legacy application and being inclusive of A2A ASR setup/configuration. Most of our customers are still very much in a legacy app world for LOB applications they move to Azure at this point of time.

**Comment by mwasham** [comment]
One of the key goals of this was to also cover resiliency from the perspective of scale too so scale sets do fit the architecture well.

"The web application needs to have the ability to scale as we grow. That aspect of the cloud will allow this to be a reality?"

To make this solution geo-redundant we could use ASR to replicate the SQL VMs, and the runbook to recreate the scale set programmatically.
 
I don't know if we want to go deep on this though (just in the WDS most likely) - since ASR is covered pretty thoroughly in the other MCWs.

Thoughts?

**Comment by DawnmarieDesJardins** [comment]
@bendq 
Hi Ben, bringing this back to your attention for response.
