### ISSUE TITLE
Deployed VMs do not use Auto Shutdown

### ISSUE THREAD

**Issue by pankaj1102** [microsoft/MCW-Building-a-resilient-IaaS-architecture#36]
All resource templates and instructions should include instructions to configure Auto Shutdown for VMs since this lab is going to be most likely run in a pre-funded training subscription or MSDN subscription both of which could not afford to have VMs running overnight.

**Comment by DawnmarieDesJardins** [comment]
@mwasham @Jeff-Opsgility 
Please review/advise.

**Comment by paulopsgility** [comment]
I don't believe any of the MCWs use auto-shutdown. We will need to discuss this for the next update if we want to make this change. It is not a matter of just turning it on, there are risks associated with this (VMs being shutdown in the middle of the lab etc).

**Comment by DawnmarieDesJardins** [comment]
@waltermyersiii @ChongRX78 
Thanks Paul!
Walter & Chong,
Please review this open issue and provide comments/suggestions.  Should we mark this as an enhancement for the next update?
Thanks, Dawnmarie

**Comment by paulopsgility** [comment]
These cloud workshops are used all over the world. For us to implement auto-shutdown would require us to either prompt for users to select their timezone or ask them to configure it correctly and/or code it into an ARM template in the case of pre-deployed VMs. 

For manual setup, people are welcome to setup auto-shutdown if they desire it. For automation, I don't want to force this. If someone doesn't input the correct timezone it has a high probability of shutting down in the middle of their lab. There are cleanup instructions at the end of the lab so this really shouldn't be an issue unless someone is spanning a single day for a 4 hour lab. In those rare cases I would rather have the proctor coaching the customer on how to minimize costs across all of the deployed resources rather than just automating it for VMs only.
