### ISSUE TITLE
September 2019 - Content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Building-a-resilient-IaaS-architecture#39]
This MCW is scheduled for content update.
Opsgility - please review current content and open issues #12 & #34 and provide your recommended updates for SME review.

**Comment by paulopsgility** [comment]
- Improve "Before the hands-on lab" to streamline deployment and configuration
- Update all powershell scripts from AzureRM* to new Az* cmdlets
- Change all deployments to use a "Deploy to Azure" button instead of clicking through Github repos to get to the deployment
- Remove external dependency on 3rd party Github repo
- Change VMs to use managed disks, see issue #12 
- Enhance instructions around SQLAOG setup for clarity, see issue #34 
- General updates and fixes

**Comment by jtuliani** [comment]
Additional enhancements in Sept 2019 Update:

- HA domain controller VM deployment significantly streamlined (disks are now provisioned with the VMs and set up by the AddDC script, removing the need to RDP to each VM).
- Fixed network settings so both VNET1 and VNET2 are updated to use the new HA domain controllers
- WebVMs are now domain joined
- Removed set to enable non-secure dynamic DNS registrations (not needed since SQL VMs are domain joined)
 - The redundant SQL and Web tiers are deployed in parallel, saving about 30-40 minutes of  student idle time
- Removed unnecessary and confusing 'Allow forwarded traffic' instruction from VNet peering
- AddDC script no longer contains sensitive credentials, they're passed as parameters instead
- The HA web tier now actually uses the HA database
- Replaced 'Click' with 'Select'

**Comment by DawnmarieDesJardins** [comment]
Closing issue with update merge to master.
